version: '3.8'

services:

  postgres:
    container_name: postgres
    build:
      context: postgresql
      dockerfile: Dockerfile
    image: bscpaz/sgt-db
    #restart: always
    volumes:
      - /var/lib/docker/volumes/postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./postgresql/.env    
    networks:
      - sgt-network
    ports:
      - 5432:5432

  # sgt-app:
  #   container_name: sgt-app
  #   build:
  #     context: app
  #     dockerfile: Dockerfile
  #   image: bscpaz/sgt-app
  #   networks:
  #     - sgt-network
  #   depends_on:
  #     - postgres

networks:
  sgt-network:
    driver: bridge