spring:
  datasource:
    username: sgt
    password: sgt    
    #url: jdbc:postgresql://localhost:5432/sgt 
    url: jdbc:postgresql://sgt-db:5432/sgt
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: public
